---
# Configuración de Apache para Moodle
- name: Crear directorio raíz del documento
  file:
    path: "/var/www/{{ moodleDomain }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags: [ apache ]

- name: Configurar VirtualHost de Apache para Moodle
  template:
    src: "../files/moodleApache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ moodleDomain }}.conf"
  tags: [ apache ]

- name: Habilitar el nuevo sitio
  shell: /usr/sbin/a2ensite {{ moodleDomain }}.conf
  tags: [ apache ]

- name: Reiniciar Apache para aplicar cambios
  service:
    name: apache2
    state: restarted
  tags: [ apache ]

# Configuración de la base de datos para Moodle
- name: Crear base de datos para Moodle
  mysql_db:
    name: "{{ moodleDBName }}"
    state: present
    login_user: root
    login_password: "{{ mysqlRootPassword }}"
  tags: [ mysql ]

- name: Crear usuario de la base de datos para Moodle
  mysql_user:
    name: "{{ moodleDBUser }}"
    password: "{{ moodleDBPassword }}"
    priv: "{{ moodleDBName }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysqlRootPassword }}"
  tags: [ mysql ]

# Descargar y configurar Moodle
- name: Descargar Moodle
  get_url:
    url: "https://download.moodle.org/stable{{ moodle_version }}/moodle-latest-{{ moodle_version }}.tgz"
    dest: "/tmp/moodle.tgz"

- name: Extraer Moodle
  unarchive:
    src: "/tmp/moodle.tgz"
    dest: "/var/www/{{ moodleDomain }}"
    remote_src: yes
    creates: "/var/www/{{ moodleDomain }}/moodle"
  tags: [ moodle ]

- name: Establecer permisos adecuados
  file:
    path: "/var/www/{{ moodleDomain }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ moodle ]

- name: Configurar archivo de configuración de Moodle
  template:
    src: "../files/moodleConfig.php.j2"
    dest: "/var/www/{{ moodleDomain }}/moodle/config.php"
  tags: [ moodle ]

# Reiniciar MySQL para aplicar cambios
- name: Reiniciar MySQL para aplicar cambios
  service:
    name: mariadb
    state: restarted
  tags: [ mysql ]