---
- name: Configuración Apache y Nginx
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - include_tasks: tasks/common.yml
    - include_tasks: tasks/apache.yml
    - include_tasks: tasks/nginx.yml
